version: "3.5"
services:
  api:
    container_name: virtualization-and-container.api
    image: virtualization-and-container.api
    build:
      context: .
    ports:
      - "8080:8080"
  mongo:
    container_name: virtualization-and-container.mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: container-and-virtualization
    ports:
      - "27017:27017"
  web:
    container_name: virtualization-and-container.nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf